skip_output = ['meta', 'execution', 'empty_summary']

[pre-commit]
parallel = true

[pre-commit.commands.biome]
glob = "*"
run = "node_modules/.bin/biome check --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}"
