output = ['summary']

[pre-commit]
parallel = true

[pre-commit.commands.biome]
glob = "*.{json,ts}"
run = "node_modules/.bin/biome check --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}"

[pre-commit.commands.test]
glob = "*.ts"
run = "bun test"

[pre-commit.commands.typos]
glob = "*.{md,mdoc,mdx}"
run = "typos {staged_files}"

[pre-commit.commands.actionlint]
glob = ".github/workflows/*.yml"
run = "actionlint {staged_files}"
