name: 🪲 Bug report
description: Create a report to help us improve
title: "[BUG] "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.

        Please fill in as much of the following form as you're able.
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior, preferably a sample code snippet.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What is the expected behavior? Why is that the expected behavior?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Provide screenshots if applicable.
  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: Provide the SDK version (e.g., 0.2.0).
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Environment (please complete the following information):**
        - OS: [e.g. iOS, Android, Windows]
        - Browser [e.g. Chrome, Safari]
        - Version [e.g. 22]
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Provide details about the environment (OS, Browser, Version).
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
