name: 💡 Feature request
description: Suggest an idea for this project
title: "[FEATURE] "
body:
  - type: markdown
    attributes:
      value: |
        **Is your feature request related to a problem? Please describe.**
        
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Describe the problem that your feature request is related to.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Describe the solution you'd like**
        A clear and concise description of what you want to happen.
  - type: textarea
    id: solution-description
    attributes:
      label: Solution Description
      description: Describe the solution you would like.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: alternatives-description
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
