name: Release

on:
  release:
    types: [published]

jobs:
  npm-publish:
    name: Publish to NPM
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2
      - run: bun install

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          registry-url: https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Run tests
        run: bun test

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: Run e2e tests
        run: bun test:e2e
        
      - name: Build artifacts
        run: node_modules/.bin/tsup

      - name: Publish to npm
        id: publish
        run: npm publish --provenance --access public --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
