name: Release

on:
  release:
    types: [published]

jobs:
  npm-publish:
    name: Publish to NPM
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
      - run: bun install

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          registry-url: https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

      - name: Run tests
        run: bun test
        
      - name: Build artifacts
        run: node_modules/.bin/tsup

      - name: Publish to npm
        id: publish
        run: npm publish --provenance --access public --no-git-checks
