name: Bun
on:
  pull_request:
    paths:
      - "**/*.ts"
      - "bun.lock" # dependencies have changed
  push:
    branches:
      - main

jobs:
  bun-test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: oven-sh/setup-bun@v2
      - run: bun install

      - name: Run tests
        run: bun run test -- --coverage --coverage-reporter=lcov --coverage-dir=coverage

  bun-test-e2e:
    name: E2E Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: oven-sh/setup-bun@v2
      - run: bun install

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - run: bun test:e2e
